stages:
  - lint
  - test
  # - build
  # - pages
  # - deploy

image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  # Cache the pip and installed package directories
  paths:
    - .cache/pip
    - venv/

default:
  # Scripts that runs before all jobs
  before_script:
    - python --version  # For debugging
    - python -m venv venv
    - source venv/bin/activate
    - python -m pip install --upgrade pip
    - pip install wheel
    - pip install -r requirements.txt

lint:
  stage: lint
  script:
    - pip install black
    - black src/mt/
    - black --check src/mt

test:
  stage: test
  script:
    - python -m unittest discover -s src/mt/tests -p "test_*.py"

# Only run the build stage if the test stage passes, the branch is main
# build:
#   stage: build
#   script:
#     - pip install build
#     - python -m build --wheel
#   artifacts:
#     paths:
#       - dist/*.whl
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# pages:
#   stage: pages
#   script:
#     - pip install sphinx sphinx-rtd-theme
#     - cd doc
#     - make html
#     - mv build/html/ ../public/
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production
